[functions]
  external_node_modules = ["sharp"]
  included_files = ["node_modules/sharp/**/*"]

[context.app]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"